In [17]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])


In [12]:
np.intersect1d(n1,n2)

array([50, 60])

In [13]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [14]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [18]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2])

100

In [19]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [20]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [21]:
#BASIC ADDITION
import numpy as np
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [22]:
#MULTILPCATION
import numpy as np
n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [23]:
#SUBTRACTION
import numpy as np
n1=np.array([10,20,30])
n1=n1-2
n1

array([ 8, 18, 28])

In [24]:
import numpy as np
n1=np.array([10,20,30])
n1=n1/2
n1

[ 5. 10. 15.]


In [27]:
#MEAN
import numpy as np
n1=np.array([10,20,30,40,50,70])
np.mean(n1)

36.666666666666664

In [29]:
#MEDIAN
import numpy as np
n1=np.array([10,30,50,70,90,110])
np.median(n1)

60.0

In [33]:
#STANDARD DEVIATION
import numpy as np
n1=np.array([11,22,44,56,78,87])
np.std(n1)

27.475241379993168

In [34]:
import numpy as np
n1=np.array([10,20,35,46,67])
np.save('final_numpy_array',n1)
np.load('final_numpy_array.npy')

array([10, 20, 35, 46, 67])

In [35]:
#PANDAS
import pandas as pd
s1=pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [43]:
import pandas as pd
s1=pd.Series([1,2,3,4,5],index=['a','boom','c','d','e',])
s1

a       1
boom    2
c       3
d       4
e       5
dtype: int64

In [45]:
s2=pd.Series([1,2,3,4,5,6])
s2[3]

4

In [46]:
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s1[-3:]

6    7
7    8
8    9
dtype: int64

In [47]:
import pandas as pd
pd.DataFrame({"Name":['Bob','Sam','Anne'],"Marks":[76,25,92]})

Name  Marks
0   Bob     76
1   Sam     25
2  Anne     92

In [48]:
 iris=pd.read_csv('iris.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'

In [50]:
iris.head()

NameError: name 'iris' is not defined